// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EndToEndDB.Data.EndToEnd
{
    public partial class AnnonymousSuggestion
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? Votes { get; set; }
        public string UserName { get; set; }
    }
}