// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EndToEndDB.Data.EndToEnd
{
    public partial class EndtoEndContext : DbContext
    {
        public EndtoEndContext()
        {
        }

        public EndtoEndContext(DbContextOptions<EndtoEndContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AnnonymousSuggestion> AnnonymousSuggestion { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AnnonymousSuggestion>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.Description)
                    .HasMaxLength(250)
                    .HasColumnName("Description ");

                entity.Property(e => e.Title).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}